### ISSUE TITLE
Change a[:,:] = 1 behaviour to be a[BandRange,BandRange] = 1

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaMatrices/BandedMatrices.jl#11]
The overloading `a[:,:]` to mean only the banded entries is confusing, so I think it should be changed to `a[BandRange,BandRange]`.  `a[:,:] = 0` would be allowed, as well as `a[:,:] = M` where `M` has zeros in the appropriate entries.

**Comment by dlfivefifty** [comment]
@gasagna Any thoughts on this change?

**Comment by marcusdavidwebb** [comment]
I don't see what a[:,:] can be confused with. If you change a[:,:] to a[BandRange,BandRange], then afterwards, how do you anticipate a[:,:] and a[BandRange,BandRange] to differ?

**Comment by marcusdavidwebb** [comment]
Do you want a[:,:] = 1 to turn a[:,:] into a full matrix of ones?

**Comment by dlfivefifty** [comment]
a[:,:] = 1 would through an error, though a[:,:] = 0 would work

**Comment by dlfivefifty** [comment]
This is consistent with the difference between a[:,2] and a[BandRange,2].  Also, a[:,:] = M where M is an AbstractMarix would work if M has zeros in the right place.

**Comment by dlfivefifty** [comment]
The issue is that BandedMatrix <: AbstractMatrix and if you only know a is an AbstractMatrix, you'd expect a[:,:] = 1 to change every entry

**Comment by marcusdavidwebb** [comment]
Oh I see, so a[:,:] = 1 should throw an error because when you have a banded matrix type you shouldn't be able assign (nonzero) values to elements outside the bands. So there are three approaches I can see:

1. You cannot make assignments outside the bands. i.e. a[i,j] = 1 throws an error if i,j is outside the bands.
2. If you make an assignment outside the bands then the bandwidth is changed to accommodate that. Perhaps rebuilding a.data. I'm not sure.
3. If you make an assignment outside the bands then those entries remain zero regardless. (this is what currently happens)

I think that 1 disobeys what SetIndex is meant to do for an AbstractArray subtype. However, if someone is working with banded matrices, surely they should be aware of and in control of what their bandwidths are and would prefer method 1 to catch errors? Anyone who wants number 2's functionality should change the bandwidth manually before they make assignments to elements outside the bandwidth right?

**Comment by dlfivefifty** [comment]
1. Is already the case, though a[i,j] = 0 is allowed

**Comment by marcusdavidwebb** [comment]
Oh yeah, I'm sorry you're right. Well the ability to say a[:,:] = 1 is silly then. This should throw an error to be consistent. Surely?

**Comment by marcusdavidwebb** [comment]
My only point now would be that BandRange is a bit of a long string. a[BRange,BRange]?

**Comment by dlfivefifty** [comment]
It's already there as BandRange.  A user can always do BR = BandRange

**Comment by marcusdavidwebb** [comment]
Ok good. To reiterate the only non-ignorant thing I said: I don't think the violation of SetIndex intentions for AbstractMatrix is such a big deal because anyone using BandedMatrices is aware of the bandwidths being used and will want to stay within them in almost all cases.

**Comment by dlfivefifty** [comment]
Actually, I think the syntax should be `a[BandRange] = 1` to follow `a[band(0)] = 1`.

**Comment by gasagna** [comment]
When I wrote the `setindex` code I designed `a[:, :]` and `a[:]` to mean *all nonzero elements* in the bands. I think that what you propose now is better, although the only catch I see is that when you want to write generic code you might not know what the type of `a` is, so you would write `a[:, :] = something`. However, this would raise an error if `something` falls outside of the band.

👍🏻

**Comment by dlfivefifty** [comment]
a[BandRange] = 1 is now implemented in the tagged version 0.1
