### ISSUE TITLE
WARNING: could not import LinearAlgebra._apply_ipiv! into BandedMatrices

### ISSUE THREAD

**Issue by asinghvi17** [JuliaMatrices/BandedMatrices.jl#120]
when `using BandedMatrices`

**Comment by dlfivefifty** [comment]
What version of Julia?

**Comment by asinghvi17** [comment]
1.3 (that's probably why)

**Comment by dlfivefifty** [comment]
I generally don’t try to support releases until they reach release candidate stage: sometimes breaking changes are undone so it’s too difficult.

As soon as 1.3-rc1 is released I’ll go through and make sure everything works.

If it’s urgent, I’m happy to accept a PR to fix it. Basically you’ll want to find where that function is called and compare with how LinearAlgebra has changed since 1.2.

**Comment by asinghvi17** [comment]
Not urgent at all, just something I'd noticed.  Thanks!
